### ISSUE TITLE
Fail to start casspoke due to authentication

### ISSUE THREAD

**Issue by hadarizi** [criteo/casspoke#2]
Hi,
I'm trying to start casspoke exporter but i'm failing with the following:

ERROR com.criteo.nosql.casspoke.cassandra.CassandraMonitor - Cannot create connection to cluster com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host cc-ext-cassandra-0.XXXX/10.2.6.4:9042: Host cc-ext-cassandra-0.XXXX/10.2.6.4:9042 requires authentication, but no authenticator found in Cluster configuration

`cc-ext-cassandra-0:/opt/aa/site_1.0/installs/casspoke # java -jar casspoke-1.3.jar config.yml
[main] INFO com.criteo.nosql.casspoke.Main - Loading yaml config from config.yml
[main] INFO com.criteo.nosql.casspoke.Main - DNS discovery will be used
[main] INFO com.criteo.nosql.casspoke.Main - Starting an http server on port 8080
[main] INFO com.criteo.nosql.casspoke.Main - Loading runner CassandraRunner
[main] INFO com.criteo.nosql.casspoke.Main - Run CassandraRunner
[main] INFO com.criteo.nosql.casspoke.cassandra.CassandraRunner - A new Monitor for Service {cluster='cc-ext-cassandra'} will be created.
[main] INFO com.datastax.driver.core.GuavaCompatibility - Detected Guava >= 19 in the classpath, using modern compatibility layer
[main] INFO com.datastax.driver.core.ClockFactory - Using native clock to generate timestamps.
[main] INFO com.datastax.driver.core.utils.UUIDs - PID obtained through native call to getpid(): 53299
[main] INFO com.datastax.driver.core.NettyUtil - Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
[main] ERROR com.criteo.nosql.casspoke.cassandra.CassandraMonitor - Cannot create connection to cluster
com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host cc-ext-cassandra-0.XXXX/10.2.6.4:9042: Host cc-ext-cassandra-0.XXXX/10.2.6.4:9042 requires authentication, but no authenticator found in Cluster configuration
        at com.datastax.driver.core.AuthProvider$1.newAuthenticator(AuthProvider.java:40)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:259)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:244)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
        at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
        at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1302)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1083)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1006)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
[main] INFO com.criteo.nosql.casspoke.cassandra.CassandraRunner - UPDATE_TOPOLOGY took 31702 ms`

config.yml is attached:
[config.txt](https://github.com/criteo/casspoke/files/3734005/config.txt)

curl --noproxy "*" localhost:8080/metrics
# HELP cassandra_latency latencies observed by instance and command
# TYPE cassandra_latency summary
# HELP cassandra_up Are the servers up?
# TYPE cassandra_up gauge

How can I resolve it? 
Thanks!

**Comment by erebe** [comment]
Hello,

Sorry for the delay, I was in vacation.

Regarding your issue, it seems the authentification haven't been implemented, which is sad as it seems easy to add.
I will see if we can add auth support "soon"

**Comment by ashangit** [comment]
Support added in #3
